server:
  port: 9002
spring:
  application:
    name: user-consumer-feign
  zipkin:
    base-url: http://localhost:7004
  sleuth:
    sampler:
      percentage: 1.0
eureka:
  client:
    service-url:
      defaultZone: http://root:ok@localhost:7001/eureka/
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true
name: zhuge
